/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.guilhermedelemos.ac;

public class App {

    public static final String GREETING = "Olá mundo";

    public String getGreeting() {
        return GREETING;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
