language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11
  - openjdk12

addons:
  sonarcloud:
    organization: "guilhermedelemos-github"

script:
  - ./gradlew sonarqube
